services:
  db:
    image: postgres:16-alpine
    container_name: wms-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thado123
      POSTGRES_DB: WMS_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d WMS_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis-wms
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: wms-backend:latest
    container_name: wms-backend
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/static/file_import_item:/app/static/file_import_item
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  celery-worker-logic:
    image: wms-backend:latest
    container_name: wms-celery-logic
    command: >
      celery -A app.core.celery_app.celery_app worker
      -Q logic
      --loglevel=INFO
      --concurrency=4
      --prefetch-multiplier=1
      --max-tasks-per-child=200
      -n logic@%h
    env_file:
      - ./backend/.env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_BROKER_RESULT_URL: redis://redis:6379/2
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/static/file_import_item:/app/static/file_import_item
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    restart: unless-stopped

  celery-worker-status:
    image: wms-backend:latest
    container_name: wms-celery-status
    command: >
      celery -A app.core.celery_app.celery_app worker
      -Q status
      --loglevel=INFO
      --concurrency=2
      --prefetch-multiplier=1
      --max-tasks-per-child=500
      -n status@%h
    env_file:
      - ./backend/.env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_BROKER_RESULT_URL: redis://redis:6379/2
    volumes:
      - ./backend/logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://10.73.231.5:8001
    container_name: wms-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
