"""big update inbound order

Revision ID: e495d531169c
Revises: 0c92286d2be7
Create Date: 2026-08-12 11:34:12.792991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e495d531169c'
down_revision: Union[str, None] = '0c92286d2be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbound_order_allocation', sa.Column('unit_id', sa.Integer(), nullable=False))
    op.drop_index('ix_inbound_order_allocation_from_location_id', table_name='inbound_order_allocation')
    op.drop_index('ix_inbound_order_allocation_to_location_id', table_name='inbound_order_allocation')
    op.create_index(op.f('ix_inbound_order_allocation_unit_id'), 'inbound_order_allocation', ['unit_id'], unique=False)
    op.drop_constraint('inbound_order_allocation_to_location_id_fkey', 'inbound_order_allocation', type_='foreignkey')
    op.drop_constraint('inbound_order_allocation_from_location_id_fkey', 'inbound_order_allocation', type_='foreignkey')
    op.create_foreign_key(None, 'inbound_order_allocation', 'unit', ['unit_id'], ['id'])
    op.drop_column('inbound_order_allocation', 'from_location_id')
    op.drop_column('inbound_order_allocation', 'to_location_id')
    op.add_column('inbound_order_detail', sa.Column('from_location_id', sa.Integer(), nullable=True))
    op.add_column('inbound_order_detail', sa.Column('to_location_id', sa.Integer(), nullable=True))
    op.drop_index('ix_inbound_order_detail_expiry_date', table_name='inbound_order_detail')
    op.drop_index('ix_inbound_order_detail_lot_number', table_name='inbound_order_detail')
    op.create_index(op.f('ix_inbound_order_detail_from_location_id'), 'inbound_order_detail', ['from_location_id'], unique=False)
    op.create_index(op.f('ix_inbound_order_detail_to_location_id'), 'inbound_order_detail', ['to_location_id'], unique=False)
    op.drop_constraint('inbound_order_detail_item_id_fkey', 'inbound_order_detail', type_='foreignkey')
    op.drop_constraint('fk_inbound_order_detail_unit_id_unit', 'inbound_order_detail', type_='foreignkey')
    op.create_foreign_key(None, 'inbound_order_detail', 'location', ['to_location_id'], ['id'])
    op.create_foreign_key(None, 'inbound_order_detail', 'location', ['from_location_id'], ['id'])
    op.drop_column('inbound_order_detail', 'unit_id')
    op.drop_column('inbound_order_detail', 'item_id')
    op.drop_column('inbound_order_detail', 'quantity')
    op.drop_column('inbound_order_detail', 'expiry_date')
    op.drop_column('inbound_order_detail', 'lot_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbound_order_detail', sa.Column('lot_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('inbound_order_detail', sa.Column('expiry_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('inbound_order_detail', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('inbound_order_detail', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('inbound_order_detail', sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inbound_order_detail', type_='foreignkey')
    op.drop_constraint(None, 'inbound_order_detail', type_='foreignkey')
    op.create_foreign_key('fk_inbound_order_detail_unit_id_unit', 'inbound_order_detail', 'unit', ['unit_id'], ['id'])
    op.create_foreign_key('inbound_order_detail_item_id_fkey', 'inbound_order_detail', 'item', ['item_id'], ['id'])
    op.drop_index(op.f('ix_inbound_order_detail_to_location_id'), table_name='inbound_order_detail')
    op.drop_index(op.f('ix_inbound_order_detail_from_location_id'), table_name='inbound_order_detail')
    op.create_index('ix_inbound_order_detail_lot_number', 'inbound_order_detail', ['lot_number'], unique=False)
    op.create_index('ix_inbound_order_detail_expiry_date', 'inbound_order_detail', ['expiry_date'], unique=False)
    op.drop_column('inbound_order_detail', 'to_location_id')
    op.drop_column('inbound_order_detail', 'from_location_id')
    op.add_column('inbound_order_allocation', sa.Column('to_location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inbound_order_allocation', sa.Column('from_location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inbound_order_allocation', type_='foreignkey')
    op.create_foreign_key('inbound_order_allocation_from_location_id_fkey', 'inbound_order_allocation', 'location', ['from_location_id'], ['id'])
    op.create_foreign_key('inbound_order_allocation_to_location_id_fkey', 'inbound_order_allocation', 'location', ['to_location_id'], ['id'])
    op.drop_index(op.f('ix_inbound_order_allocation_unit_id'), table_name='inbound_order_allocation')
    op.create_index('ix_inbound_order_allocation_to_location_id', 'inbound_order_allocation', ['to_location_id'], unique=False)
    op.create_index('ix_inbound_order_allocation_from_location_id', 'inbound_order_allocation', ['from_location_id'], unique=False)
    op.drop_column('inbound_order_allocation', 'unit_id')
    # ### end Alembic commands ###
