"""update lot details

Revision ID: 0c92286d2be7
Revises: be65937ad4e3
Create Date: 2026-08-12 11:06:25.857749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c92286d2be7'
down_revision: Union[str, None] = 'be65937ad4e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Optional legacy indexes (may not exist on fresh databases).
    op.execute("DROP INDEX IF EXISTS ix_inbound_alloc_from_location")
    op.execute("DROP INDEX IF EXISTS ix_inbound_alloc_to_location")
    op.execute("DROP INDEX IF EXISTS ix_inbound_detail_id_status")
    op.execute("DROP INDEX IF EXISTS ix_item_stock_location_active")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_item_stock_location_active', 'item_stock', ['location_id'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('ix_inbound_detail_id_status', 'inbound_order_detail', ['id', 'status'], unique=False)
    op.create_index('ix_inbound_alloc_to_location', 'inbound_order_allocation', ['to_location_id'], unique=False)
    op.create_index('ix_inbound_alloc_from_location', 'inbound_order_allocation', ['from_location_id'], unique=False)
    # ### end Alembic commands ###
