"""update outbound status

Revision ID: 1e0c2682650e
Revises: e2f3a4b5c6d7
Create Date: 2026-08-13 16:47:29.309838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e0c2682650e'
down_revision: Union[str, None] = 'e2f3a4b5c6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbound_order_status', table_name='outbound_order')
    op.drop_column('outbound_order', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbound_order', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_index('ix_outbound_order_status', 'outbound_order', ['status'], unique=False)
    # ### end Alembic commands ###
