"""change_status_inbound_order

Revision ID: 39c14afeeb62
Revises: 0496687a917b
Create Date: 2026-08-11 15:03:35.505141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c14afeeb62'
down_revision: Union[str, None] = '0496687a917b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inbound_order_status', table_name='inbound_order')
    op.drop_column('inbound_order', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbound_order', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_index('ix_inbound_order_status', 'inbound_order', ['status'], unique=False)
    # ### end Alembic commands ###
