"""add_unit_and_item_unit_tables

Revision ID: 3f81006dff3b
Revises: 5d148e983cbc
Create Date: 2026-08-04 00:40:16.474817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f81006dff3b'
down_revision: Union[str, None] = '5d148e983cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_id'), 'unit', ['id'], unique=False)
    op.create_table('item_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('conversion_factor', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_unit_id'), 'item_unit', ['id'], unique=False)
    op.create_index(op.f('ix_item_unit_item_id'), 'item_unit', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_unit_unit_id'), 'item_unit', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_unit_unit_id'), table_name='item_unit')
    op.drop_index(op.f('ix_item_unit_item_id'), table_name='item_unit')
    op.drop_index(op.f('ix_item_unit_id'), table_name='item_unit')
    op.drop_table('item_unit')
    op.drop_index(op.f('ix_unit_id'), table_name='unit')
    op.drop_table('unit')
    # ### end Alembic commands ###
