"""add_more_field_to_notification2

Revision ID: 747d1f476051
Revises: 63e34052639c
Create Date: 2026-09-22 00:52:26.908879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747d1f476051'
down_revision: Union[str, None] = '63e34052639c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'notification',
        sa.Column(
            'notification_type',
            sa.String(length=50),
            nullable=False,
            server_default='alert',
        ),
    )
    op.alter_column('notification', 'notification_type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'notification_type')
    # ### end Alembic commands ###
