"""add qr_type

Revision ID: 13f3b26a2411
Revises: 05ee581abd1e
Create Date: 2026-08-25 16:01:33.054231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f3b26a2411'
down_revision: Union[str, None] = '05ee581abd1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_code', sa.Column('qr_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qr_code', 'qr_type')
    # ### end Alembic commands ###
