"""add itemstock relation and additional field

Revision ID: 7ff8e8ad6409
Revises: 13f3b26a2411
Create Date: 2026-08-27 08:48:11.238252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ff8e8ad6409'
down_revision: Union[str, None] = '13f3b26a2411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_stock_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_stock_id', sa.Integer(), nullable=False),
    sa.Column('child_stock_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('parent_stock_id <> child_stock_id', name='chk_no_self_reference'),
    sa.ForeignKeyConstraint(['child_stock_id'], ['item_stock.id'], ),
    sa.ForeignKeyConstraint(['parent_stock_id'], ['item_stock.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_stock_id', 'child_stock_id', 'relation_type', name='uq_stock_relation')
    )
    op.create_index(op.f('ix_item_stock_relation_child_stock_id'), 'item_stock_relation', ['child_stock_id'], unique=False)
    op.create_index(op.f('ix_item_stock_relation_id'), 'item_stock_relation', ['id'], unique=False)
    op.create_index(op.f('ix_item_stock_relation_parent_stock_id'), 'item_stock_relation', ['parent_stock_id'], unique=False)
    op.create_index(op.f('ix_item_stock_relation_relation_type'), 'item_stock_relation', ['relation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_stock_relation_relation_type'), table_name='item_stock_relation')
    op.drop_index(op.f('ix_item_stock_relation_parent_stock_id'), table_name='item_stock_relation')
    op.drop_index(op.f('ix_item_stock_relation_id'), table_name='item_stock_relation')
    op.drop_index(op.f('ix_item_stock_relation_child_stock_id'), table_name='item_stock_relation')
    op.drop_table('item_stock_relation')
    # ### end Alembic commands ###
