"""create warehouse location item stock transaction tables

Revision ID: ea11c0ad6d49
Revises: 428622398633
Create Date: 2026-07-29 22:09:45.948019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea11c0ad6d49'
down_revision: Union[str, None] = '428622398633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_code'), 'warehouse', ['code'], unique=True)
    op.create_index(op.f('ix_warehouse_id'), 'warehouse', ['id'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_unit', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('supplier', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=False)
    op.create_index(op.f('ix_item_sku'), 'item', ['sku'], unique=True)
    op.create_index(op.f('ix_item_warehouse_id'), 'item', ['warehouse_id'], unique=False)
    op.create_table('zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_code'), 'zone', ['code'], unique=True)
    op.create_index(op.f('ix_zone_id'), 'zone', ['id'], unique=False)
    op.create_index(op.f('ix_zone_warehouse_id'), 'zone', ['warehouse_id'], unique=False)
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_code', sa.String(length=50), nullable=False),
    sa.Column('location_name', sa.String(length=100), nullable=False),
    sa.Column('row', sa.String(length=10), nullable=True),
    sa.Column('column', sa.String(length=10), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('node_name', sa.String(length=50), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_id'), 'location', ['id'], unique=False)
    op.create_index(op.f('ix_location_location_code'), 'location', ['location_code'], unique=True)
    op.create_index(op.f('ix_location_location_name'), 'location', ['location_name'], unique=True)
    op.create_index(op.f('ix_location_warehouse_id'), 'location', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_location_zone_id'), 'location', ['zone_id'], unique=False)
    op.create_table('item_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('lot_number', sa.String(length=50), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='available', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('quantity >= 0', name='ck_item_stock_quantity_non_negative'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_stock_expiry_date'), 'item_stock', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_item_stock_id'), 'item_stock', ['id'], unique=False)
    op.create_index(op.f('ix_item_stock_item_id'), 'item_stock', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_stock_location_id'), 'item_stock', ['location_id'], unique=False)
    op.create_index(op.f('ix_item_stock_lot_number'), 'item_stock', ['lot_number'], unique=False)
    op.create_index(op.f('ix_item_stock_status'), 'item_stock', ['status'], unique=False)
    op.create_index(op.f('ix_item_stock_stock_code'), 'item_stock', ['stock_code'], unique=True)
    op.create_table('location_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=False),
    sa.Column('to_location_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('item_stock_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['item_stock_id'], ['item_stock.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_transaction_created_by_id'), 'location_transaction', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_location_transaction_from_location_id'), 'location_transaction', ['from_location_id'], unique=False)
    op.create_index(op.f('ix_location_transaction_id'), 'location_transaction', ['id'], unique=False)
    op.create_index(op.f('ix_location_transaction_item_stock_id'), 'location_transaction', ['item_stock_id'], unique=False)
    op.create_index(op.f('ix_location_transaction_to_location_id'), 'location_transaction', ['to_location_id'], unique=False)
    op.create_index(op.f('ix_location_transaction_transaction_type'), 'location_transaction', ['transaction_type'], unique=False)
    op.drop_constraint('role_permissions_role_id_fkey', 'role_permissions', type_='foreignkey')
    op.drop_constraint('role_permissions_permission_id_fkey', 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.alter_column('roles', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('user_roles_user_id_fkey', 'user_roles', type_='foreignkey')
    op.drop_constraint('user_roles_role_id_fkey', 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key('user_roles_role_id_fkey', 'user_roles', 'roles', ['role_id'], ['id'])
    op.create_foreign_key('user_roles_user_id_fkey', 'user_roles', 'users', ['user_id'], ['id'])
    op.alter_column('roles', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key('role_permissions_permission_id_fkey', 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.create_foreign_key('role_permissions_role_id_fkey', 'role_permissions', 'roles', ['role_id'], ['id'])
    op.drop_index(op.f('ix_location_transaction_transaction_type'), table_name='location_transaction')
    op.drop_index(op.f('ix_location_transaction_to_location_id'), table_name='location_transaction')
    op.drop_index(op.f('ix_location_transaction_item_stock_id'), table_name='location_transaction')
    op.drop_index(op.f('ix_location_transaction_id'), table_name='location_transaction')
    op.drop_index(op.f('ix_location_transaction_from_location_id'), table_name='location_transaction')
    op.drop_index(op.f('ix_location_transaction_created_by_id'), table_name='location_transaction')
    op.drop_table('location_transaction')
    op.drop_index(op.f('ix_item_stock_stock_code'), table_name='item_stock')
    op.drop_index(op.f('ix_item_stock_status'), table_name='item_stock')
    op.drop_index(op.f('ix_item_stock_lot_number'), table_name='item_stock')
    op.drop_index(op.f('ix_item_stock_location_id'), table_name='item_stock')
    op.drop_index(op.f('ix_item_stock_item_id'), table_name='item_stock')
    op.drop_index(op.f('ix_item_stock_id'), table_name='item_stock')
    op.drop_index(op.f('ix_item_stock_expiry_date'), table_name='item_stock')
    op.drop_table('item_stock')
    op.drop_index(op.f('ix_location_zone_id'), table_name='location')
    op.drop_index(op.f('ix_location_warehouse_id'), table_name='location')
    op.drop_index(op.f('ix_location_location_name'), table_name='location')
    op.drop_index(op.f('ix_location_location_code'), table_name='location')
    op.drop_index(op.f('ix_location_id'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_zone_warehouse_id'), table_name='zone')
    op.drop_index(op.f('ix_zone_id'), table_name='zone')
    op.drop_index(op.f('ix_zone_code'), table_name='zone')
    op.drop_table('zone')
    op.drop_index(op.f('ix_item_warehouse_id'), table_name='item')
    op.drop_index(op.f('ix_item_sku'), table_name='item')
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_warehouse_id'), table_name='warehouse')
    op.drop_index(op.f('ix_warehouse_code'), table_name='warehouse')
    op.drop_table('warehouse')
    # ### end Alembic commands ###
