"""add_robot_task_table

Revision ID: 4d8e51f442e8
Revises: a109eb9f1110
Create Date: 2026-08-07 10:44:40.115875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d8e51f442e8'
down_revision: Union[str, None] = 'a109eb9f1110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robot_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inbound_order_detail_id', sa.Integer(), nullable=True),
    sa.Column('outbound_order_detail_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('process_code', sa.String(length=50), nullable=False),
    sa.Column('system_code', sa.String(length=50), nullable=False),
    sa.Column('task_order_detail', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inbound_order_detail_id'], ['inbound_order_detail.id'], ),
    sa.ForeignKeyConstraint(['outbound_order_detail_id'], ['outbound_order_detail.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robot_task_id'), 'robot_task', ['id'], unique=False)
    op.create_index(op.f('ix_robot_task_inbound_order_detail_id'), 'robot_task', ['inbound_order_detail_id'], unique=False)
    op.create_index(op.f('ix_robot_task_order_id'), 'robot_task', ['order_id'], unique=False)
    op.create_index(op.f('ix_robot_task_outbound_order_detail_id'), 'robot_task', ['outbound_order_detail_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_robot_task_outbound_order_detail_id'), table_name='robot_task')
    op.drop_index(op.f('ix_robot_task_order_id'), table_name='robot_task')
    op.drop_index(op.f('ix_robot_task_inbound_order_detail_id'), table_name='robot_task')
    op.drop_index(op.f('ix_robot_task_id'), table_name='robot_task')
    op.drop_table('robot_task')
    # ### end Alembic commands ###
