"""add_map_x_map_y_to_location

Revision ID: b3775d08063f
Revises: b7c9e1d3a5f2
Create Date: 2026-09-21 16:42:10.429227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3775d08063f'
down_revision: Union[str, None] = 'b7c9e1d3a5f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('map_x', sa.Integer(), nullable=True))
    op.add_column('location', sa.Column('map_y', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'map_y')
    op.drop_column('location', 'map_x')
    # ### end Alembic commands ###
