"""change_status_robottask

Revision ID: be65937ad4e3
Revises: 39c14afeeb62
Create Date: 2026-08-11 15:36:42.755582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be65937ad4e3'
down_revision: Union[str, None] = '39c14afeeb62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robot_task', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot_task', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
