"""change stocktake status

Revision ID: 05ee581abd1e
Revises: d28308e1aefa
Create Date: 2026-08-22 10:51:17.369533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ee581abd1e'
down_revision: Union[str, None] = 'd28308e1aefa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocktake',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocktake_created_by_id'), 'stocktake', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_stocktake_id'), 'stocktake', ['id'], unique=False)
    op.create_index(op.f('ix_stocktake_warehouse_id'), 'stocktake', ['warehouse_id'], unique=False)
    op.create_table('stocktake_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stocktake_id', sa.Integer(), nullable=False),
    sa.Column('item_stock_id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('desired_quantity', sa.Integer(), nullable=False),
    sa.Column('actual_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['item_stock_id'], ['item_stock.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['stocktake_id'], ['stocktake.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocktake_item_id'), 'stocktake_item', ['id'], unique=False)
    op.create_index(op.f('ix_stocktake_item_item_stock_id'), 'stocktake_item', ['item_stock_id'], unique=False)
    op.create_index(op.f('ix_stocktake_item_location_id'), 'stocktake_item', ['location_id'], unique=False)
    op.create_index(op.f('ix_stocktake_item_stocktake_id'), 'stocktake_item', ['stocktake_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocktake_item_stocktake_id'), table_name='stocktake_item')
    op.drop_index(op.f('ix_stocktake_item_location_id'), table_name='stocktake_item')
    op.drop_index(op.f('ix_stocktake_item_item_stock_id'), table_name='stocktake_item')
    op.drop_index(op.f('ix_stocktake_item_id'), table_name='stocktake_item')
    op.drop_table('stocktake_item')
    op.drop_index(op.f('ix_stocktake_warehouse_id'), table_name='stocktake')
    op.drop_index(op.f('ix_stocktake_id'), table_name='stocktake')
    op.drop_index(op.f('ix_stocktake_created_by_id'), table_name='stocktake')
    op.drop_table('stocktake')
    # ### end Alembic commands ###
