"""update outbound detail status

Revision ID: e6c24c984f48
Revises: 1e0c2682650e
Create Date: 2026-08-13 17:04:56.905145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c24c984f48'
down_revision: Union[str, None] = '1e0c2682650e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbound_order_detail_status', table_name='outbound_order_detail')
    op.drop_column('outbound_order_detail', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbound_order_detail', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_index('ix_outbound_order_detail_status', 'outbound_order_detail', ['status'], unique=False)
    # ### end Alembic commands ###
