"""update outbound allocation location from and to

Revision ID: 73a2848af4f2
Revises: c08112bbdbe0
Create Date: 2026-08-14 14:54:04.092064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a2848af4f2'
down_revision: Union[str, None] = 'c08112bbdbe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbound_order_allocation', sa.Column('robot_task_id', sa.Integer(), nullable=True))
    op.alter_column('outbound_order_allocation', 'from_location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('outbound_order_allocation', 'to_location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_outbound_order_allocation_robot_task_id'), 'outbound_order_allocation', ['robot_task_id'], unique=False)
    op.create_foreign_key(None, 'outbound_order_allocation', 'robot_task', ['robot_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outbound_order_allocation', type_='foreignkey')
    op.drop_index(op.f('ix_outbound_order_allocation_robot_task_id'), table_name='outbound_order_allocation')
    op.alter_column('outbound_order_allocation', 'to_location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('outbound_order_allocation', 'from_location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('outbound_order_allocation', 'robot_task_id')
    # ### end Alembic commands ###
