"""add_map_table

Revision ID: dc77a404581d
Revises: 3f81006dff3b
Create Date: 2026-08-05 13:20:21.867332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc77a404581d'
down_revision: Union[str, None] = '3f81006dff3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_map_id'), 'warehouse_map', ['id'], unique=False)
    op.create_index(op.f('ix_warehouse_map_warehouse_id'), 'warehouse_map', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_warehouse_map_zone_id'), 'warehouse_map', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouse_map_zone_id'), table_name='warehouse_map')
    op.drop_index(op.f('ix_warehouse_map_warehouse_id'), table_name='warehouse_map')
    op.drop_index(op.f('ix_warehouse_map_id'), table_name='warehouse_map')
    op.drop_table('warehouse_map')
    # ### end Alembic commands ###
