"""add field for itemstock

Revision ID: 24a5b14caaf9
Revises: 7ff8e8ad6409
Create Date: 2026-08-27 09:03:37.986758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a5b14caaf9'
down_revision: Union[str, None] = '7ff8e8ad6409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_stock', sa.Column('qc_user', sa.String(length=50), nullable=True))
    op.add_column('item_stock', sa.Column('manufacturing_user', sa.String(length=50), nullable=True))
    op.add_column('item_stock', sa.Column('packing_user', sa.String(length=50), nullable=True))
    op.add_column('item_stock', sa.Column('cavity_number', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_item_stock_cavity_number'), 'item_stock', ['cavity_number'], unique=False)
    op.create_index(op.f('ix_item_stock_manufacturing_user'), 'item_stock', ['manufacturing_user'], unique=False)
    op.create_index(op.f('ix_item_stock_packing_user'), 'item_stock', ['packing_user'], unique=False)
    op.create_index(op.f('ix_item_stock_qc_user'), 'item_stock', ['qc_user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_stock_qc_user'), table_name='item_stock')
    op.drop_index(op.f('ix_item_stock_packing_user'), table_name='item_stock')
    op.drop_index(op.f('ix_item_stock_manufacturing_user'), table_name='item_stock')
    op.drop_index(op.f('ix_item_stock_cavity_number'), table_name='item_stock')
    op.drop_column('item_stock', 'cavity_number')
    op.drop_column('item_stock', 'packing_user')
    op.drop_column('item_stock', 'manufacturing_user')
    op.drop_column('item_stock', 'qc_user')
    # ### end Alembic commands ###
