"""add stocktake module models

Revision ID: d28308e1aefa
Revises: e5f6a7b8c9d0
Create Date: 2026-08-22 09:29:21.713576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd28308e1aefa'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_import_error_job_id', table_name='item_import_error')
    op.drop_table('item_import_error')
    op.drop_index('ix_item_import_staging_job_id', table_name='item_import_staging')
    op.drop_index('ix_item_import_staging_job_sku', table_name='item_import_staging')
    op.drop_table('item_import_staging')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_import_staging',
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('row_no', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('sku', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('supplier', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('base_unit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('base_quantity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('min_quantity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('max_quantity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True)
    )
    op.create_index('ix_item_import_staging_job_sku', 'item_import_staging', ['job_id', 'sku'], unique=False)
    op.create_index('ix_item_import_staging_job_id', 'item_import_staging', ['job_id'], unique=False)
    op.create_table('item_import_error',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('row_no', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('sku', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='item_import_error_pkey')
    )
    op.create_index('ix_item_import_error_job_id', 'item_import_error', ['job_id'], unique=False)
    # ### end Alembic commands ###
