"""add_task_status_and_update_robot_task

Revision ID: d426a8285129
Revises: 4d8e51f442e8
Create Date: 2026-08-07 11:15:14.013966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd426a8285129'
down_revision: Union[str, None] = '4d8e51f442e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_task_status', sa.String(length=50), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('device_code', sa.String(length=50), nullable=True),
    sa.Column('device_num', sa.Integer(), nullable=True),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.Column('shelf_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_status_id'), 'task_status', ['id'], unique=False)
    op.create_index(op.f('ix_task_status_order_id'), 'task_status', ['order_id'], unique=False)
    op.alter_column(
        'robot_task',
        'order_id',
        existing_type=sa.INTEGER(),
        type_=sa.String(length=50),
        existing_nullable=False,
        postgresql_using='order_id::text',
    )
    op.drop_column('robot_task', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot_task', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column(
        'robot_task',
        'order_id',
        existing_type=sa.String(length=50),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using='order_id::integer',
    )
    op.drop_index(op.f('ix_task_status_order_id'), table_name='task_status')
    op.drop_index(op.f('ix_task_status_id'), table_name='task_status')
    op.drop_table('task_status')
    # ### end Alembic commands ###
