"""change_status_location_of_allocation

Revision ID: 0496687a917b
Revises: f0ae84ed312e
Create Date: 2026-08-11 14:40:05.886647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0496687a917b'
down_revision: Union[str, None] = 'f0ae84ed312e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inbound_order_allocation', 'from_location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inbound_order_allocation', 'to_location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_inbound_order_allocation_status', table_name='inbound_order_allocation')
    op.drop_column('inbound_order_allocation', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbound_order_allocation', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_index('ix_inbound_order_allocation_status', 'inbound_order_allocation', ['status'], unique=False)
    op.alter_column('inbound_order_allocation', 'to_location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inbound_order_allocation', 'from_location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
