"""update outbound allocation robot task

Revision ID: c08112bbdbe0
Revises: e6c24c984f48
Create Date: 2026-08-14 12:39:39.491857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08112bbdbe0'
down_revision: Union[str, None] = 'e6c24c984f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_robot_task_outbound_order_detail_id', table_name='robot_task')
    op.drop_constraint('robot_task_outbound_order_detail_id_fkey', 'robot_task', type_='foreignkey')
    op.drop_column('robot_task', 'outbound_order_detail_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot_task', sa.Column('outbound_order_detail_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('robot_task_outbound_order_detail_id_fkey', 'robot_task', 'outbound_order_detail', ['outbound_order_detail_id'], ['id'])
    op.create_index('ix_robot_task_outbound_order_detail_id', 'robot_task', ['outbound_order_detail_id'], unique=False)
    # ### end Alembic commands ###
