"""add QR code table

Revision ID: 145027db3d7f
Revises: b7e4f2a1c8d3
Create Date: 2026-08-19 11:35:38.698937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '145027db3d7f'
down_revision: Union[str, None] = 'b7e4f2a1c8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_stock_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['item_stock_id'], ['item_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_code_code'), 'qr_code', ['code'], unique=True)
    op.create_index(op.f('ix_qr_code_id'), 'qr_code', ['id'], unique=False)
    op.create_index(op.f('ix_qr_code_item_id'), 'qr_code', ['item_id'], unique=False)
    op.create_index(op.f('ix_qr_code_item_stock_id'), 'qr_code', ['item_stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qr_code_item_stock_id'), table_name='qr_code')
    op.drop_index(op.f('ix_qr_code_item_id'), table_name='qr_code')
    op.drop_index(op.f('ix_qr_code_id'), table_name='qr_code')
    op.drop_index(op.f('ix_qr_code_code'), table_name='qr_code')
    op.drop_table('qr_code')
    # ### end Alembic commands ###
