"""add manufacturing_machine to item_stock

Revision ID: 3eb0c1679875
Revises: b7c9e1d3a5f2
Create Date: 2026-09-16 22:02:12.132422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb0c1679875'
down_revision: Union[str, None] = 'b7c9e1d3a5f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_stock', sa.Column('manufacturing_machine', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_item_stock_manufacturing_machine'), 'item_stock', ['manufacturing_machine'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_stock_manufacturing_machine'), table_name='item_stock')
    op.drop_column('item_stock', 'manufacturing_machine')
    # ### end Alembic commands ###
