"""add_max_min_quantity_to_item

Revision ID: 98e353d7265b
Revises: 35c81f142795
Create Date: 2026-08-06 22:13:50.511495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e353d7265b'
down_revision: Union[str, None] = '35c81f142795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'item',
        sa.Column('max_quantity', sa.Integer(), nullable=False, server_default='999999'),
    )
    op.add_column(
        'item',
        sa.Column('min_quantity', sa.Integer(), nullable=False, server_default='10'),
    )
    op.alter_column('item', 'max_quantity', server_default=None)
    op.alter_column('item', 'min_quantity', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'min_quantity')
    op.drop_column('item', 'max_quantity')
    # ### end Alembic commands ###
