"""add_inbound_outbound_history_and_item_stock_fk

Revision ID: 5d148e983cbc
Revises: <auto>
Create Date: 2026-08-04 00:27:36.593393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d148e983cbc'
down_revision: Union[str, None] = '<auto>'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_order_created_by_id'), 'inbound_order', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_inbound_order_id'), 'inbound_order', ['id'], unique=False)
    op.create_index(op.f('ix_inbound_order_order_code'), 'inbound_order', ['order_code'], unique=True)
    op.create_index(op.f('ix_inbound_order_status'), 'inbound_order', ['status'], unique=False)
    op.create_index(op.f('ix_inbound_order_warehouse_id'), 'inbound_order', ['warehouse_id'], unique=False)
    op.create_table('outbound_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_order_created_by_id'), 'outbound_order', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_outbound_order_id'), 'outbound_order', ['id'], unique=False)
    op.create_index(op.f('ix_outbound_order_order_code'), 'outbound_order', ['order_code'], unique=True)
    op.create_index(op.f('ix_outbound_order_status'), 'outbound_order', ['status'], unique=False)
    op.create_index(op.f('ix_outbound_order_warehouse_id'), 'outbound_order', ['warehouse_id'], unique=False)
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inbound_order_id', sa.Integer(), nullable=True),
    sa.Column('outbound_order_id', sa.Integer(), nullable=True),
    sa.Column('old_status', sa.String(length=50), nullable=False),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inbound_order_id'], ['inbound_order.id'], ),
    sa.ForeignKeyConstraint(['outbound_order_id'], ['outbound_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_created_by_id'), 'history', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_history_id'), 'history', ['id'], unique=False)
    op.create_index(op.f('ix_history_inbound_order_id'), 'history', ['inbound_order_id'], unique=False)
    op.create_index(op.f('ix_history_new_status'), 'history', ['new_status'], unique=False)
    op.create_index(op.f('ix_history_old_status'), 'history', ['old_status'], unique=False)
    op.create_index(op.f('ix_history_outbound_order_id'), 'history', ['outbound_order_id'], unique=False)
    op.create_table('inbound_order_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inbound_order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail_type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inbound_order_id'], ['inbound_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_order_detail_detail_type'), 'inbound_order_detail', ['detail_type'], unique=False)
    op.create_index(op.f('ix_inbound_order_detail_id'), 'inbound_order_detail', ['id'], unique=False)
    op.create_index(op.f('ix_inbound_order_detail_inbound_order_id'), 'inbound_order_detail', ['inbound_order_id'], unique=False)
    op.create_index(op.f('ix_inbound_order_detail_status'), 'inbound_order_detail', ['status'], unique=False)
    op.create_table('outbound_order_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outbound_order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail_type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['outbound_order_id'], ['outbound_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_order_detail_detail_type'), 'outbound_order_detail', ['detail_type'], unique=False)
    op.create_index(op.f('ix_outbound_order_detail_id'), 'outbound_order_detail', ['id'], unique=False)
    op.create_index(op.f('ix_outbound_order_detail_outbound_order_id'), 'outbound_order_detail', ['outbound_order_id'], unique=False)
    op.create_index(op.f('ix_outbound_order_detail_status'), 'outbound_order_detail', ['status'], unique=False)
    op.create_table('inbound_order_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inbound_order_detail_id', sa.Integer(), nullable=False),
    sa.Column('item_stock_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=False),
    sa.Column('to_location_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['from_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['inbound_order_detail_id'], ['inbound_order_detail.id'], ),
    sa.ForeignKeyConstraint(['item_stock_id'], ['item_stock.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_order_allocation_from_location_id'), 'inbound_order_allocation', ['from_location_id'], unique=False)
    op.create_index(op.f('ix_inbound_order_allocation_id'), 'inbound_order_allocation', ['id'], unique=False)
    op.create_index(op.f('ix_inbound_order_allocation_inbound_order_detail_id'), 'inbound_order_allocation', ['inbound_order_detail_id'], unique=False)
    op.create_index(op.f('ix_inbound_order_allocation_item_stock_id'), 'inbound_order_allocation', ['item_stock_id'], unique=False)
    op.create_index(op.f('ix_inbound_order_allocation_status'), 'inbound_order_allocation', ['status'], unique=False)
    op.create_index(op.f('ix_inbound_order_allocation_to_location_id'), 'inbound_order_allocation', ['to_location_id'], unique=False)
    op.create_table('outbound_order_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outbound_order_detail_id', sa.Integer(), nullable=False),
    sa.Column('item_stock_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=False),
    sa.Column('to_location_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['from_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['item_stock_id'], ['item_stock.id'], ),
    sa.ForeignKeyConstraint(['outbound_order_detail_id'], ['outbound_order_detail.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_order_allocation_from_location_id'), 'outbound_order_allocation', ['from_location_id'], unique=False)
    op.create_index(op.f('ix_outbound_order_allocation_id'), 'outbound_order_allocation', ['id'], unique=False)
    op.create_index(op.f('ix_outbound_order_allocation_item_stock_id'), 'outbound_order_allocation', ['item_stock_id'], unique=False)
    op.create_index(op.f('ix_outbound_order_allocation_outbound_order_detail_id'), 'outbound_order_allocation', ['outbound_order_detail_id'], unique=False)
    op.create_index(op.f('ix_outbound_order_allocation_status'), 'outbound_order_allocation', ['status'], unique=False)
    op.create_index(op.f('ix_outbound_order_allocation_to_location_id'), 'outbound_order_allocation', ['to_location_id'], unique=False)
    op.add_column('item_stock', sa.Column('inbound_order_detail_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_item_stock_inbound_order_detail_id'), 'item_stock', ['inbound_order_detail_id'], unique=False)
    op.create_foreign_key(None, 'item_stock', 'inbound_order_detail', ['inbound_order_detail_id'], ['id'])
    op.drop_index('ix_location_transaction_created_by_id', table_name='transaction')
    op.drop_index('ix_location_transaction_from_location_id', table_name='transaction')
    op.drop_index('ix_location_transaction_id', table_name='transaction')
    op.drop_index('ix_location_transaction_item_stock_id', table_name='transaction')
    op.drop_index('ix_location_transaction_to_location_id', table_name='transaction')
    op.drop_index('ix_location_transaction_transaction_type', table_name='transaction')
    op.create_index(op.f('ix_transaction_created_by_id'), 'transaction', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_transaction_from_location_id'), 'transaction', ['from_location_id'], unique=False)
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_item_stock_id'), 'transaction', ['item_stock_id'], unique=False)
    op.create_index(op.f('ix_transaction_to_location_id'), 'transaction', ['to_location_id'], unique=False)
    op.create_index(op.f('ix_transaction_transaction_type'), 'transaction', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_transaction_type'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_to_location_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_item_stock_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_from_location_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_created_by_id'), table_name='transaction')
    op.create_index('ix_location_transaction_transaction_type', 'transaction', ['transaction_type'], unique=False)
    op.create_index('ix_location_transaction_to_location_id', 'transaction', ['to_location_id'], unique=False)
    op.create_index('ix_location_transaction_item_stock_id', 'transaction', ['item_stock_id'], unique=False)
    op.create_index('ix_location_transaction_id', 'transaction', ['id'], unique=False)
    op.create_index('ix_location_transaction_from_location_id', 'transaction', ['from_location_id'], unique=False)
    op.create_index('ix_location_transaction_created_by_id', 'transaction', ['created_by_id'], unique=False)
    op.drop_constraint(None, 'item_stock', type_='foreignkey')
    op.drop_index(op.f('ix_item_stock_inbound_order_detail_id'), table_name='item_stock')
    op.drop_column('item_stock', 'inbound_order_detail_id')
    op.drop_index(op.f('ix_outbound_order_allocation_to_location_id'), table_name='outbound_order_allocation')
    op.drop_index(op.f('ix_outbound_order_allocation_status'), table_name='outbound_order_allocation')
    op.drop_index(op.f('ix_outbound_order_allocation_outbound_order_detail_id'), table_name='outbound_order_allocation')
    op.drop_index(op.f('ix_outbound_order_allocation_item_stock_id'), table_name='outbound_order_allocation')
    op.drop_index(op.f('ix_outbound_order_allocation_id'), table_name='outbound_order_allocation')
    op.drop_index(op.f('ix_outbound_order_allocation_from_location_id'), table_name='outbound_order_allocation')
    op.drop_table('outbound_order_allocation')
    op.drop_index(op.f('ix_inbound_order_allocation_to_location_id'), table_name='inbound_order_allocation')
    op.drop_index(op.f('ix_inbound_order_allocation_status'), table_name='inbound_order_allocation')
    op.drop_index(op.f('ix_inbound_order_allocation_item_stock_id'), table_name='inbound_order_allocation')
    op.drop_index(op.f('ix_inbound_order_allocation_inbound_order_detail_id'), table_name='inbound_order_allocation')
    op.drop_index(op.f('ix_inbound_order_allocation_id'), table_name='inbound_order_allocation')
    op.drop_index(op.f('ix_inbound_order_allocation_from_location_id'), table_name='inbound_order_allocation')
    op.drop_table('inbound_order_allocation')
    op.drop_index(op.f('ix_outbound_order_detail_status'), table_name='outbound_order_detail')
    op.drop_index(op.f('ix_outbound_order_detail_outbound_order_id'), table_name='outbound_order_detail')
    op.drop_index(op.f('ix_outbound_order_detail_id'), table_name='outbound_order_detail')
    op.drop_index(op.f('ix_outbound_order_detail_detail_type'), table_name='outbound_order_detail')
    op.drop_table('outbound_order_detail')
    op.drop_index(op.f('ix_inbound_order_detail_status'), table_name='inbound_order_detail')
    op.drop_index(op.f('ix_inbound_order_detail_inbound_order_id'), table_name='inbound_order_detail')
    op.drop_index(op.f('ix_inbound_order_detail_id'), table_name='inbound_order_detail')
    op.drop_index(op.f('ix_inbound_order_detail_detail_type'), table_name='inbound_order_detail')
    op.drop_table('inbound_order_detail')
    op.drop_index(op.f('ix_history_outbound_order_id'), table_name='history')
    op.drop_index(op.f('ix_history_old_status'), table_name='history')
    op.drop_index(op.f('ix_history_new_status'), table_name='history')
    op.drop_index(op.f('ix_history_inbound_order_id'), table_name='history')
    op.drop_index(op.f('ix_history_id'), table_name='history')
    op.drop_index(op.f('ix_history_created_by_id'), table_name='history')
    op.drop_table('history')
    op.drop_index(op.f('ix_outbound_order_warehouse_id'), table_name='outbound_order')
    op.drop_index(op.f('ix_outbound_order_status'), table_name='outbound_order')
    op.drop_index(op.f('ix_outbound_order_order_code'), table_name='outbound_order')
    op.drop_index(op.f('ix_outbound_order_id'), table_name='outbound_order')
    op.drop_index(op.f('ix_outbound_order_created_by_id'), table_name='outbound_order')
    op.drop_table('outbound_order')
    op.drop_index(op.f('ix_inbound_order_warehouse_id'), table_name='inbound_order')
    op.drop_index(op.f('ix_inbound_order_status'), table_name='inbound_order')
    op.drop_index(op.f('ix_inbound_order_order_code'), table_name='inbound_order')
    op.drop_index(op.f('ix_inbound_order_id'), table_name='inbound_order')
    op.drop_index(op.f('ix_inbound_order_created_by_id'), table_name='inbound_order')
    op.drop_table('inbound_order')
    # ### end Alembic commands ###
